CREATE SCHEMA INVENTARIO;

CREATE TABLE INVENTARIO.INGRESOCOMPUTADORES(
SECUENCIAL INT NOT NULL IDENTITY PRIMARY KEY,
CODIGOINTERNO VARCHAR(20) NOT NULL,
CUADADDEUBICACION VARCHAR(20) NOT NULL,
DESCRIPCION VARCHAR(20) NOT NULL,
MEMORIARAM INT NOT NULL,
PROCESADOR VARCHAR(40) NOT NULL,
DISCODURO INT NOT NULL,
LICENCIADO BIT NOT NULL,
OFFICE BIT NOT NULL,
MARCA VARCHAR(15) NOT NULL,
MODELO VARCHAR(20) NOT NULL,
SERIE VARCHAR(30) NOT NULL,
PARTICULARIDAD VARCHAR(30) NOT NULL,
ESTADO BIT NOT NULL,
NODEFACTURA INT NOT NULL,
VALORFACTURA INT NOT NULL,
FECHAADQUISICION DATE NOT NULL,
OBSERVACIONES VARCHAR(100) NOT NULL
);

CREATE TABLE INVENTARIO.INGRESOVARIOS(
SECUENCIAL INT NOT NULL IDENTITY PRIMARY KEY,
CODIGOINTERNO VARCHAR(20) NOT NULL,
CUADADDEUBICACION VARCHAR(20) NOT NULL,
DESCRIPCION VARCHAR(20) NOT NULL,
MARCA VARCHAR(15) NOT NULL,
MODELO VARCHAR(20) NOT NULL,
SERIE VARCHAR(30) NOT NULL,
PARTICULARIDAD VARCHAR(30) NOT NULL,
ESTADO BIT NOT NULL,
NODEFACTURA INT NOT NULL,
VALORFACTURA INT NOT NULL,
FECHAADQUISICION DATE NOT NULL,
OBSERVACIONES VARCHAR(100) NOT NULL
);

CREATE TABLE INVENTARIO.ASIGNACIONCOMPUTADORES(
SECUENCIAL INT NOT NULL IDENTITY PRIMARY KEY,
RESPONSABLE VARCHAR(40) NOT NULL,
CODIGOINTERNO VARCHAR(20) NOT NULL,
TIEMPOINICIO DATE NOT NULL,
TIEMPOFIN DATE NOT NULL
);

CREATE TABLE INVENTARIO.ASIGNACIONVARIOS(
SECUENCIAL INT NOT NULL IDENTITY PRIMARY KEY,
RESPONSABLE VARCHAR(40) NOT NULL,
CODIGOINTERNO VARCHAR(20) NOT NULL,
TIEMPOINICIO DATE NOT NULL,
TIEMPOFIN DATE NOT NULL
);

CREATE TABLE INVENTARIO.BAJADEEQUIPOSCOMPUTADORES(
SECUENCIAL INT NOT NULL IDENTITY PRIMARY KEY,
TIPO VARCHAR(20) NOT NULL,
RESPONSABLE VARCHAR(30) NOT NULL,
CODIGOINTERNO VARCHAR(20) NOT NULL,
);

CREATE TABLE INVENTARIO.BAJADEEQUIPOSVARIOS(
SECUENCIAL INT NOT NULL IDENTITY PRIMARY KEY,
TIPO VARCHAR(20) NOT NULL,
RESPONSABLE VARCHAR(30) NOT NULL,
CODIGOINTERNO VARCHAR(20) NOT NULL,
);

CREATE TABLE INVENTARIO.MANTENIMIENTOCOMPUTADORES(
SECUENCIAL INT NOT NULL IDENTITY PRIMARY KEY,
TIPO VARCHAR(20) NOT NULL,
RESPONSABLE VARCHAR(30) NOT NULL,
CODIGOINTERNO VARCHAR(20) NOT NULL,
);

CREATE TABLE INVENTARIO.MANTENIMIENTOVARIOS(
SECUENCIAL INT NOT NULL IDENTITY PRIMARY KEY,
TIPO VARCHAR(20) NOT NULL,
RESPONSABLE VARCHAR(30) NOT NULL,
CODIGOINTERNO VARCHAR(20) NOT NULL,
);

CREATE TABLE INVENTARIO.ITEM(
SECUENCIAL INT NOT NULL IDENTITY PRIMARY KEY,
CODIGO VARCHAR(20) NOT NULL,
TIPOITEM VARCHAR(30) NOT NULL,
CATEGORIAITEM VARCHAR(20) NOT NULL
);